### ISSUE TITLE
Submitted form browsing on portal giving error

### ISSUE THREAD

**Issue by saadaan** [JhulFramework/PHPServer4ODK#4]
Hi,

I tested your code. The installation, download to collect, and upload a submission to server are all OK. However, when I try to view the submission on the portal, I am getting this error:

Jhul\Components\EX\Sys\Handlers\Debug
ERROR_NO_READ_ACCES to field "_modules\main\models\data\M::ik"
Error(Fatal) - 1
/var/www/required/odk/0.1/framework/jhul/Jhul/Components/Database/Store/Data/_Base.php:112

Can you help me out about what is going wrong?

Thanks,
Saad

**Comment by JhulFramework** [comment]
To fix that error i need to update the code. Right now i have no plan on working on it.
Note : The code does not supports form submission with file(s) so it might be usless

Regards,
Manish

**Comment by saadaan** [comment]
Hi Manish,

Thanks a lot of the response. There is no file upload in my form. I am trying to make the code work in the simplest possible way, as a first step. The form I submitted only have 1 text and 1 numeric field, that's all! The interface was also OK for login and stuff, only after submission it started giving issue.

Is there some working server running anywhere which I can see/replicate? I reckon something is wrong with my installation method or file/dir permissions, that's why the error is coming. Just need small help to make it work, if possible for you. Would be extremely grateful!

Thanks,
Saad

**Comment by JhulFramework** [comment]
I think, its not installation error. I changed column name in database, but i forgot to update it in code.
I'll fix it my free time.

If you don't mind , i would like to know your use of it(organization or personal). My reason for abandoning this code was, nobody using it.

regards,
Manish

**Comment by saadaan** [comment]
Great!

I have rolled out at least 50 ODK installations, and almost all of them need a smarter interface than Aggregate. I have been building dashboards on top of Aggregate, but its high dependency on Aggregate's db schema is a big problem. I have been looking for an alternate to Aggregate, preferably in PHP/MySQL since long time. If you can fix this, great! If you know a better working solution, please do point me towards it.

Many thanks Manish!

**Comment by JhulFramework** [comment]
i updated the code.
Check it again and let me know, if error is gone.
